### 금융상품 갱신 여부 예측하는 ANN 

Churn_Modelling.csv 파일을 보면, 고객 정보와 해당 고객이 금융상품을 갱신했는지 안했는지의 여부에 대한 데이터가 있다.

이 데이터를 가지고 갱신여부를 예측하는 딥러닝을 구성하시오.

# Neural Networks and Deep Learning

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
import os

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
os.chdir('/content/drive/MyDrive/kdigital2/deeplearning/data')

In [6]:
df = pd.read_csv('Churn_Modelling.csv')

In [7]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [8]:
# nan 있는지 확인

In [9]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
# X, y 로 분리

In [11]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [12]:
y = df['Exited']

In [13]:
X = df.iloc[ : ,  3: -2+1]

In [14]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [15]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [16]:
# 문자열 데이터는 숫자로 바꿔줘야 한다.

In [17]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [18]:
X['Geography'].nunique()

3

In [19]:
X['Gender'].nunique()

2

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
l_encoder = LabelEncoder()

In [23]:
X['Gender'] = l_encoder.fit_transform( X['Gender'] )

In [24]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
from sklearn.compose import ColumnTransformer

In [29]:
ct = ColumnTransformer( [ ('encoder', OneHotEncoder(), [1]) ] , 
                       remainder= 'passthrough' )

In [30]:
X = ct.fit_transform(X)

In [31]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
#  germany, spain 
#    0        0 
#    1        0
#    0        1 

In [34]:
X = X[ : ,  1 :   ]

In [35]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [38]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [43]:
# 피처 스케일링 한다.

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
sc_X = MinMaxScaler()

In [42]:
X = sc_X.fit_transform(X)

In [44]:
# 학습용과 검증용으로 데이터를 나눈다

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [47]:
X_train.shape

(8000, 11)

In [48]:
X_test.shape

(2000, 11)

In [50]:
y_train.shape

(8000,)

In [51]:
y_test.shape

(2000,)

In [56]:
X_train[0, : ]

array([0.        , 1.        , 0.634     , 0.        , 0.21621622,
       0.5       , 0.        , 0.33333333, 1.        , 0.        ,
       0.81917353])

In [52]:
# Part 2 - Now let's make the ANN!

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [60]:
model = Sequential()

In [61]:
model.add( Dense(units = 6, activation='relu', input_shape = (11,) )  )

In [62]:
model.add( Dense(units= 8 , activation= tf.nn.relu ) )

In [63]:
model.add(  Dense(units= 1, activation= 'sigmoid' ) )

In [64]:
# compile

In [65]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'] )

In [66]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dense_4 (Dense)             (None, 8)                 56        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


In [68]:
12 * 6

72

In [69]:
model.fit(X_train, y_train, epochs = 20, batch_size = 10)

Epoch 1/20
800/800 [==============================] - 3s 2ms/step - loss: 0.5531 - accuracy: 0.7640
Epoch 2/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4847 - accuracy: 0.7960
Epoch 3/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4562 - accuracy: 0.7993
Epoch 4/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4427 - accuracy: 0.8050
Epoch 5/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4368 - accuracy: 0.8100
Epoch 6/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4316 - accuracy: 0.8129
Epoch 7/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4274 - accuracy: 0.8140
Epoch 8/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4239 - accuracy: 0.8164
Epoch 9/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.8200
Epoch 10/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4186 - accuracy: 0.8216

In [71]:
# 모델 평가

In [70]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 0s 1ms/step - loss: 0.3624 - accuracy: 0.8530


[0.3624242842197418, 0.8529999852180481]

In [72]:
# 컨퓨전 매트릭스 확인

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [74]:
y_pred = model.predict(X_test)

In [75]:
y_pred

array([[0.30097747],
       [0.314327  ],
       [0.22450587],
       ...,
       [0.16943353],
       [0.16685331],
       [0.19470108]], dtype=float32)

In [81]:
y_pred = (y_pred > 0.5).astype(int)

In [82]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [76]:
X_test

array([[1.        , 0.        , 0.494     , ..., 1.        , 1.        ,
        0.96429754],
       [0.        , 0.        , 0.346     , ..., 1.        , 0.        ,
        0.64351406],
       [0.        , 1.        , 0.712     , ..., 1.        , 1.        ,
        0.37863951],
       ...,
       [0.        , 1.        , 0.456     , ..., 1.        , 0.        ,
        0.70767563],
       [1.        , 0.        , 0.6       , ..., 1.        , 1.        ,
        0.05632988],
       [1.        , 0.        , 0.446     , ..., 1.        , 0.        ,
        0.96478724]])

In [77]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [84]:
cm = confusion_matrix( y_test, y_pred)

In [85]:
cm

array([[1537,   58],
       [ 236,  169]])

In [87]:
(1537+169) / cm.sum()

0.853

In [88]:
accuracy_score(y_test, y_pred)

0.853

## 다음 신규 데이터를 통해 분류해 보자

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40
- Tenure: 3
- Balance: 60000
- Number of Products: 2
- Has Credit Card: Yes
- Is Active Member: Yes
- Estimated Salary: 50000

In [90]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [91]:
new_data = np.array( [600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000] )

In [92]:
new_data.shape

(10,)

In [94]:
new_data = new_data.reshape( 1, 10)

In [97]:
new_data[ : , 2 ] = l_encoder.transform(new_data[ : , 2 ])

In [98]:
new_data

array([['600', 'France', '1', '40', '3', '60000', '2', '1', '1', '50000']],
      dtype='<U21')

In [100]:
new_data = ct.transform(new_data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  "X does not have valid feature names, but"


In [101]:
new_data

array([['1.0', '0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1',
        '1', '50000']], dtype='<U32')

In [103]:
new_data = new_data[ : ,  1 :  ]

In [104]:
new_data

array([['0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype='<U32')

In [106]:
new_data = sc_X.transform(new_data)

In [107]:
new_data

array([[0.        , 0.        , 0.5       , 1.        , 0.2972973 ,
        0.3       , 0.23914092, 0.33333333, 1.        , 1.        ,
        0.24996597]])

In [109]:
y_pred = model.predict(new_data)

In [110]:
y_pred

array([[0.08408403]], dtype=float32)

In [113]:
y_pred = (y_pred > 0.5).astype(int)

In [114]:
y_pred

array([[0]])

### 용어 정리

epoch

- 한 번의 epoch는 신경망에서 전체 데이터 셋에 대해 forward pass/backward pass 과정을 거친 것을 말함. 즉, 전체 데이터 셋에 대해 한 번 학습을 완료한 상태


batch_size

메모리의 한계와 속도 저하 때문에 대부분의 경우에는 한 번의 epoch에서 모든 데이터를 한꺼번에 집어넣을 수는 없습니다. 그래서 데이터를 나누어서 주게 되는데 이때 몇 번 나누어서 주는가를 iteration, 각 iteration마다 주는 데이터 사이즈를 batch size라고 합니다.

출처: https://www.slideshare.net/w0ong/ss-82372826

### GridSearch 를 이용한, 최적의 하이퍼 파라미터 찾기

In [115]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


In [116]:
def build_classifier(optimizer) :
  # 모델링
  model = Sequential()
  model.add(Dense(units= 6, activation='relu', input_shape = (11,)))
  model.add(Dense(units= 8, activation='relu'))
  model.add(Dense(units= 1, activation='sigmoid'))
  model.compile(optimizer= optimizer, loss= 'binary_crossentropy', metrics=['accuracy'])
  return model

In [120]:
model = KerasClassifier(build_fn= build_classifier)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


In [122]:
my_parameters = {'epochs' : [30, 50], 'batch_size':[10,20], 'optimizer' : ['adam', 'rmsprop']}

In [123]:
grid_search = GridSearchCV(estimator= model, param_grid= my_parameters, scoring='accuracy')

In [124]:
grid_search.fit(X_train, y_train)

Epoch 1/30
640/640 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7459
Epoch 2/30
640/640 [==============================] - 2s 2ms/step - loss: 0.4721 - accuracy: 0.7980
Epoch 3/30
640/640 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.8003
Epoch 4/30
640/640 [==============================] - 2s 2ms/step - loss: 0.4464 - accuracy: 0.8039
Epoch 5/30
640/640 [==============================] - 1s 2ms/step - loss: 0.4366 - accuracy: 0.8086
Epoch 6/30
640/640 [==============================] - 1s 2ms/step - loss: 0.4286 - accuracy: 0.8130
Epoch 7/30
640/640 [==============================] - 2s 2ms/step - loss: 0.4249 - accuracy: 0.8159
Epoch 8/30
640/640 [==============================] - 2s 2ms/step - loss: 0.4201 - accuracy: 0.8181
Epoch 9/30
640/640 [==============================] - 1s 2ms/step - loss: 0.4169 - accuracy: 0.8189
Epoch 10/30
640/640 [==============================] - 1s 2ms/step - loss: 0.4141 - accuracy: 0.8205

GridSearchCV(estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x7f4a96cf9450>,
             param_grid={'batch_size': [10, 20], 'epochs': [30, 50],
                         'optimizer': ['adam', 'rmsprop']},
             scoring='accuracy')

In [125]:
grid_search.best_params_

{'batch_size': 20, 'epochs': 50, 'optimizer': 'adam'}

In [126]:
grid_search.best_score_

0.84825

In [128]:
model2 = grid_search.best_estimator_